function H = furuta_Hjac(in1,Vm)
%furuta_Hjac
%    H = furuta_Hjac(IN1,Vm)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    29-Jun-2026 00:34:53

H = reshape([1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0],[2,5]);
end
