function hmeas = furuta_meas(in1,Vm)
%FURUTA_MEAS
%    HMEAS = FURUTA_MEAS(IN1,Vm)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    29-Jun-2026 00:34:53

al = in1(2,:);
th = in1(1,:);
hmeas = [th;al];
end
